# Generated by Django 5.1 on 2024-09-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('howmany', models.IntegerField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Catering',
            },
        ),
        migrations.DeleteModel(
            name='TestCategory',
        ),
    ]
