# Generated by Django 5.1 on 2024-09-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weds', '0003_underwater'),
    ]

    operations = [
        migrations.CreateModel(
            name='venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
                ('standing_capacity', models.IntegerField()),
                ('seating_capting', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('India', 'India'), ('Australia', 'Australia'), ('Maldives', 'Maldives'), ('US', 'US'), ('Asia', 'Asia'), ('Dubai', 'Dubai')], max_length=250)),
                ('pincode', models.IntegerField()),
                ('booking_type', models.CharField(choices=[('First Hslf', 'First Half'), ('Second Half', 'Second Hslf'), ('Full time', 'Full time')], max_length=200)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'venue',
            },
        ),
    ]
