# Generated by Django 5.1 on 2024-09-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weds', '0004_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('line', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'contact',
            },
        ),
        migrations.CreateModel(
            name='makeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('wedding_date', models.DateField()),
                ('hair', models.CharField(choices=[('Bride', 'Bride'), ('Wedding Party', 'Wedding Party'), ('Flower girl', 'Flower girl')], max_length=200)),
                ('makeup_services', models.CharField(choices=[('Bride', 'Bride'), ('Wedding Party', 'Wedding Party'), ('Flower girl', 'Flower girl')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'makeup',
            },
        ),
    ]
